export {
  animalImportIssueDetails,
  animalImportPendingFromMissingEventAnimals,
  animalImportRows,
  animalImportSummary,
  ambiguousTableQuestion,
  domainDateOnly,
  domainDateTime,
  domainImportCriticalRows,
  domainImportReadyRows,
  domainImportResultMessage,
  domainImportRows,
  domainLine,
  domainParsedDate,
  domainRowValues,
  domainStatusActive,
  domainTableSummary,
  domainText,
  domainTime,
  importKey,
  normalizeDomainEventType,
  normalizeDomainFinanceType,
  stockImportIssueDetails,
  stockImportRows,
  stockImportSummary,
  tabularImportIssueDetails,
  tabularImportRows,
  tabularImportSummary,
  validCpf,
  validDomainAnimalCategory,
  validDomainSex,
  validDomainStatus,
  type DomainImportSaveStats
} from "@/services/whatsapp/confirmation-message";
