import { decimalNumberPattern } from "@/lib/whatsapp/nlp-numbers";

export const BOT_EXAMPLES = [
  "- Mimosa deu 15 litros de leite hoje",
  "- Adicionar vaca Mimosa com brinco B-043, fêmea, gestante, raça Girolando",
  "- Vendi leite por 900 reais",
  "- Comprei ração por 300 reais",
  "- Entrou 10 sacos de ração no estoque",
  "- Quais vacas estao no lote Lactacao 1",
  "- Criar lote Bezerras",
  "- João entrou às 7:30"
];

export const questionByField: Record<string, string> = {
  animal_codigo: "Qual é o brinco ou código do animal?",
  litros: "Quantos litros foram produzidos?",
  produto: "Qual medicamento, vacina ou manejo foi feito?",
  valor: "Qual foi o valor?",
  descricao: "Qual é a descrição do registro?",
  item_nome: "Qual item do estoque?",
  campo_alterado: "Qual dado do animal deseja atualizar?",
  novo_valor: "Qual novo valor deve ficar no cadastro do animal?",
  mae_nome: "Quem é a mãe desse animal?",
  pai_nome: "Quem é o pai desse animal?",
  genealogia_campo: "Você quer alterar mãe, pai ou os dois?",
  quantidade: "Qual quantidade?",
  unidade: "Qual unidade deseja usar?Exemplo: saco, kg ou unidade.",
  funcionario_nome: "Qual funcionário?",
  telefone: "Qual é o WhatsApp do funcionário?Envie com DDD.",
  funcao: "Qual e a funcao/cargo do funcionario? Exemplo: vaqueiro, gerente, ordenhador.",
  data_admissao: "Qual e a data de admissao? Envie DD/MM/AAAA ou responda 2 para usar hoje.",
  pagamento_tipo: "Esse pagamento e salario, diaria, adiantamento, bonus ou outro?",
  periodo_pagamento: "Esse pagamento e referente a qual periodo? 1 - Mes atual, 2 - Mes anterior, 3 - Informar outro.",

  ponto_tipo: "Foi entrada ou saída?",
  horario: "Qual horário? Envie por exemplo: 7:30 ou 17:00.",
  categoria_animal: "Qual é a categoria do animal?Ex: vaca, bezerro ou touro.",
  nome: "Qual e o nome ou apelido do animal? Responda 2 para pular.",
  peso: "Qual e o peso do animal? Responda 2 para pular.",
  sexo: "Qual e o sexo do animal? 1 - Macho 2 - Femea 3 - Pular.",
  fase: "Quer informar a fase?Ex: lactação, seca, gestante, vazia, crescimento, engorda ou 2 para pular.",
  raca: "Quer informar a raça?Envie o nome da raça ou 2 para pular.",
  lote_animal: "Quer informar o lote?Envie o nome do lote já cadastrado ou 2 para pular.",
  lote_nome: "Qual sera o nome do lote?",
  data_nascimento: "Quer informar o nascimento?Envie a data (DD/MM/AAAA ou AAAA-MM-DD) ou 2 para pular.",
  observacoes: "Quer informar observacoes ou historico do animal? Responda 2 para pular."
};

export const animalWords = "(?:vacas?|vca|animais|animal|animau|gado|bois?|boii|touros?|bezerros?|bezero|bezerras?|novilhas?|novila|matriz|matrizes|reprodutor(?:es)?|femeas?|machos?|maxos?|brinco)";
export const animalOptionalFields = ["sexo", "nome", "peso", "fase", "raca", "lote_animal", "data_nascimento", "observacoes"];
export const animalCategories = new Set(["vaca", "vacas", "vca", "boi", "bois", "boii", "bezerro", "bezerros", "bezero", "bezerra", "bezerras", "novilha", "novilhas", "novila", "touro", "touros", "matriz", "matrizes", "reprodutor", "reprodutores", "animal", "animais", "animau"]);
export const animalCategoryMap: Record<string, string | undefined> = {
  vaca: "vaca",
  vacas: "vaca",
  vca: "vaca",
  boi: "boi",
  bois: "boi",
  boii: "boi",
  bezerro: "bezerro",
  bezerros: "bezerro",
  bezero: "bezerro",
  bezerra: "bezerro",
  bezerras: "bezerro",
  novilha: "novilha",
  novilhas: "novilha",
  novila: "novilha",
  touro: "touro",
  touros: "touro",
  matriz: "vaca",
  matrizes: "vaca",
  reprodutor: "touro",
  reprodutores: "touro"
};
export const animalSexMap: Record<string, string | undefined> = {
  femea: "femea",
  femeas: "femea",
  feme: "femea",
  f: "femea",
  feminino: "femea",
  macho: "macho",
  machos: "macho",
  maxo: "macho",
  maxos: "macho",
  m: "macho",
  masculino: "macho"
};
export const animalPhaseMap: Record<string, string | undefined> = {
  lactacao: "lactacao",
  lactante: "lactacao",
  leite: "lactacao",
  seca: "seca",
  gestante: "gestante",
  prenha: "gestante",
  vazia: "vazia",
  crescimento: "crescimento",
  recria: "crescimento",
  engorda: "engorda",
  nao_aplicavel: "nao_aplicavel",
  inaplicavel: "nao_aplicavel"
};
export const animalCodePattern = /^[A-Z0-9]+(?:-[A-Z0-9]+)*$/;
export const stockUnitWords = "(?:sacos?|sakos?|sc|kg|kilos?|k|quilos?|gramas?|g|litros?|litos?|l|ml|mililitros?|caixas?|cx|doses?|fardos?|galoes?|galo|galao|frascos?|rolos?|un|und|unids?|unidades?)";
export const stockUnitAfterQuantityPattern = new RegExp(`\\b(${decimalNumberPattern})\\s*(${stockUnitWords})\\b`, "i");
export const stockItemHintPattern = /\b(?:racao|ração|milho|feno|sal|mineral|aftosa|vacina|remedio|remédio|medicamento|antibiotico|insumo|silagem|suplemento|diesel|oleo|veneno|carrapaticida|arame|poste|postes|brinco|brincos|identificacao|seringa|seringas|luva|luvas|ureia|concentrado|nucleo)\b/;
export const forbiddenAnimalCodes = new Set([
  "vaca",
  "vacas",
  "animal",
  "animais",
  "boi",
  "bois",
  "touro",
  "touros",
  "bezerro",
  "bezerros",
  "bezerra",
  "bezerras",
  "novilha",
  "novilhas",
  "macho",
  "femea",
  "femeas",
  "rebanho",
  "rancho",
  "fazenda",
  "que",
  "quem",
  "qual",
  "quais",
  "todas",
  "todos",
  "toda",
  "todo",
  "as",
  "os",
  "a",
  "o",
  "de",
  "da",
  "do",
  "das",
  "dos",
  "lista",
  "listar",
  "listagem",
  "dashboard",
  "geral",
  "relatorio",
  "relatorios",
  "relatirio",
  "relatirios",
  "resumo",
  "fechamento",
  "aconteceu",
  "historico",
  "historia",
  "evento",
  "eventos",
  "registro",
  "registros",
  "estoque",
  "um",
  "uma",
  "pariu",
  "pariram",
  "parto",
  "partos",
  "tiveram",
  "inseminacao",
  "inseminacoes",
  "inseminada",
  "inseminadas",
  "inseminado",
  "inseminados",
  "gestante",
  "gestantes",
  "gestacao",
  "prenhe",
  "prenhas",
  "prenhes",
  "gravida",
  "gravidas",
  "cobertura",
  "coberturas",
  "recentes",
  "recente",
  "antigo",
  "antigos",
  "antiga",
  "antigas",
  "tempo",
  "pre",
  "preparto",
  "morreu",
  "protocolo",
  "reteste",
  "fundo",
  "curral",
  "pasto",
  "piquete",
  "manha",
  "tarde",
  "noite",
  "ordenha",
  "primeira",
  "segunda",
  "terceira",
  "com",
  "nome",
  "foi",
  "era",
  "corrigir",
  "corrige",
  "corrija",
  "errado",
  "incorreto",
  "troca",
  "trocar",
  "ajusta",
  "ajustar",
  "valor",
  "quantidade",
  "agora",
  "anteontem",
  "amanha",
  "hj",
  "dia",
  "mes",
  "semana",
  "lote",
  "status",
  "nascimento",
  "nasceu",
  "prenha",
  "seca",
  "lactante",
  "lactacao",
  "hoje",
  "ontem",
  "vacina",
  "brucelose",
  "raiva",
  "clostridial",
  "medicamento",
  "remedio",
  "tratamento",
  "manejo",
  "terramicina",
  "aftosa",
  "ftosa",
  "vermifugo",
  "antibiotico",
  "dipirona",
  "carrapaticida",
  "suplemento",
  "dose",
  "doses",
  "doente",
  "febre",
  "diarreia",
  "mastite",
  "carrapato",
  "cio",
  "prenhez",
  "inseminacao",
  "cobertura",
  "veterinario",
  "mancando",
  "ordenhei",
  "tirei",
  "tirou",
  "produziu",
  "deu",
  "registrei",
  "registrar",
  "litro",
  "ente",
  "nimal",
  "ultima",
  "pata",
  "casco",
  "vacinei",
  "racao",
  "milho",
  "feno",
  "sal",
  "mineral",
  "estoque",
  "litros",
  "kg",
  "saco",
  "sacos",
  "dose",
  "doses",
  "fardo",
  "fardos"
]);
