module.exports = function loadBotTestSection(context) {
  with (context) {
    function financeParser(phrase, expected) {
      return { module: "financeiro", phrase, expected };
    }

    function eventParser(phrase, expected, extra = {}) {
      return { module: "eventos", phrase, expected, ...extra };
    }

    const financeHumanParserTests = [
      financeParser("vendi leite por 900 reais", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 900, descricao: "leite", data_referencia: "hoje" }),
      financeParser("venda de leite 900", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 900, descricao: "leite" }),
      financeParser("recebi 800 da venda de leite", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 800, descricao: "leite" }),
      financeParser("entrada 500 venda de queijo", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 500, descricao: "queijo" }),
      financeParser("vendi uma vaca por 5000", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 5000, descricao: "vaca" }),
      financeParser("recebemos 1200", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 1200 }),
      financeParser("entrou 300 no caixa", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 300 }),
      financeParser("ganhei 750 com leite", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 750, descricao: "leite" }),
      financeParser("venda animal B-002 por 4500", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 4500, descricao: "animal" }),
      financeParser("cliente pagou 650", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 650 }),
      financeParser("recebi 1.200 reais", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 1200 }),
      financeParser("recebi R$ 1.200,50", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 1200.5 }),
      financeParser("vendi leite 1200,50", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 1200.5, descricao: "leite" }),
      financeParser("venda de bezerro 800", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 800, descricao: "bezerro" }),
      financeParser("vendi bezerro por 800", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 800, descricao: "bezerro" }),
      financeParser("vendi vaca por cinco mil", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 5000, descricao: "vaca" }),
      financeParser("entrou dinheiro da venda de leite 900", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 900, descricao: "leite" }),
      financeParser("pagamento recebido 450", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 450 }),
      financeParser("recebemos do comprador 3000", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 3000 }),
      financeParser("venda de gado 7000", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 7000, descricao: "gado" }),
      financeParser("vendi esterco por 150", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 150, descricao: "esterco" }),
      financeParser("receita de leite 2500", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 2500, descricao: "leite" }),
      financeParser("receita 1200 leite", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 1200, descricao: "leite" }),
      financeParser("entrada leite 1300", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 1300, descricao: "leite" }),
      financeParser("adicionar entrada de mil reais", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 1000, descricao: "receita via WhatsApp", noMissing: true }),
      financeParser("registrar entrada de mil reais", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 1000, descricao: "receita via WhatsApp", noMissing: true }),
      financeParser("paguei salario do Joao 1500", { tipo: "PAGAMENTO_FUNCIONARIO", exactTipo: true, funcionario_nome: "Joao", valor: 1500, pagamento_tipo: "salario" }),
      financeParser("gastei 360 com vacina", { tipo: "DESPESA", exactTipo: true, valor: 360, descricao: "vacina" }),
      financeParser("saida 250 veterinario", { tipo: "DESPESA", exactTipo: true, valor: 250, descricao: "veterinario" }),
      financeParser("paguei energia 400", { tipo: "DESPESA", exactTipo: true, valor: 400, descricao: "energia" }),
      financeParser("adicionar saida de mil reais", { tipo: "DESPESA", exactTipo: true, valor: 1000, descricao: "despesa via WhatsApp", noMissing: true }),
      financeParser("registrar saida de mil reais", { tipo: "DESPESA", exactTipo: true, valor: 1000, descricao: "despesa via WhatsApp", noMissing: true }),
      financeParser("paguei mil reais de energia", { tipo: "DESPESA", exactTipo: true, valor: 1000, descricao: "energia", noMissing: true }),
      financeParser("despesa veterinario 600", { tipo: "DESPESA", exactTipo: true, valor: 600, descricao: "veterinario" }),
      financeParser("paguei 80 de combustivel", { tipo: "DESPESA", exactTipo: true, valor: 80, descricao: "combustivel" }),
      financeParser("gasto com manutencao 900", { tipo: "DESPESA", exactTipo: true, valor: 900, descricao: "manutencao" }),
      financeParser("paguei conta de luz 500", { tipo: "DESPESA", exactTipo: true, valor: 500, descricao: "luz" }),
      financeParser("paguei agua 120", { tipo: "DESPESA", exactTipo: true, valor: 120, descricao: "agua" }),
      financeParser("paguei vacina aftosa por 450", { tipo: "DESPESA", exactTipo: true, valor: 450, descricao: "aftosa" }),
      financeParser("paguei o veterinario 700", { tipo: "DESPESA", exactTipo: true, valor: 700, descricao: "veterinario" }),
      financeParser("gastei 1000 em manutencao", { tipo: "DESPESA", exactTipo: true, valor: 1000, descricao: "manutencao" }),
      financeParser("despesa com funcionario 1500", { tipo: "DESPESA", exactTipo: true, valor: 1500, descricao: "funcionario" }),
      financeParser("paguei frete 350", { tipo: "DESPESA", exactTipo: true, valor: 350, descricao: "frete" }),
      financeParser("paguei diesel 600", { tipo: "DESPESA", exactTipo: true, valor: 600, descricao: "diesel" }),
      financeParser("paguei aluguel 2000", { tipo: "DESPESA", exactTipo: true, valor: 2000, descricao: "aluguel" }),
      financeParser("gasto racao 300", { tipo: "DESPESA", exactTipo: true, valor: 300, descricao: "racao" }),
      financeParser("despesa racao 300", { tipo: "DESPESA", exactTipo: true, valor: 300, descricao: "racao" }),
      financeParser("paguei 300 na racao", { tipo: "DESPESA", exactTipo: true, valor: 300, descricao: "racao" }),
      financeParser("pagamento funcionario Joao 1500", { tipo: "PAGAMENTO_FUNCIONARIO", exactTipo: true, funcionario_nome: "Joao", valor: 1500, pagamento_tipo: "salario" }),
      financeParser("diaria do vaqueiro 120", { tipo: "DESPESA", exactTipo: true, valor: 120, descricao: "vaqueiro" }),
      financeParser("folha de pagamento 3200", { tipo: "DESPESA", exactTipo: true, valor: 3200, descricao: "folha" }),
      financeParser("recebi 300", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 300 }),
      financeParser("recebi 300,50", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 300.5 }),
      financeParser("recebi 300.50", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 300.5 }),
      financeParser("recebi R$ 300,50", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 300.5 }),
      financeParser("recebi 1.300,50", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 1300.5 }),
      financeParser("recebi 1300,50", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 1300.5 }),
      financeParser("recebi 1,300.50", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 1300.5 }),
      financeParser("paguei 1500", { tipo: "DESPESA", exactTipo: true, valor: 1500 }),
      financeParser("paguei 1.500", { tipo: "DESPESA", exactTipo: true, valor: 1500 }),
      financeParser("paguei 1.500,00", { tipo: "DESPESA", exactTipo: true, valor: 1500 }),
      financeParser("paguei R$1500", { tipo: "DESPESA", exactTipo: true, valor: 1500 }),
      financeParser("paguei R$ 1.500,00", { tipo: "DESPESA", exactTipo: true, valor: 1500 }),
      financeParser("comprei por abc", { tipo: "DESPESA", exactTipo: true, missing: ["valor"] }),
      financeParser("registrar entrada", { tipo: "RECEITA_VENDA", exactTipo: true, missing: ["valor"] }),
      financeParser("registrar saida", { tipo: "DESPESA", exactTipo: true, missing: ["valor", "descricao"] }),
      financeParser("recebi dinheiro", { tipo: "RECEITA_VENDA", exactTipo: true, missing: ["valor"] }),
      financeParser("paguei uma conta", { tipo: "DESPESA", exactTipo: true, missing: ["valor"] }),
      financeParser("saida 300", { tipo: "DESPESA", exactTipo: true, valor: 300, missing: ["descricao"] }),
      financeParser("vendi leite", { tipo: "RECEITA_VENDA", exactTipo: true, descricao: "leite", missing: ["valor"] }),
      financeParser("paguei salario", { tipo: "PAGAMENTO_FUNCIONARIO", exactTipo: true, pagamento_tipo: "salario", missing: ["funcionario", "valor"] }),
      { module: "financeiro", phrase: "900", pending: () => pendingFrom("vendi leite"), expected: { tipo: "RECEITA_VENDA", exactTipo: true, valor: 900, descricao: "leite", noMissing: true } },
      { module: "financeiro", phrase: "300", pending: () => pendingFrom("paguei energia"), expected: { tipo: "DESPESA", exactTipo: true, valor: 300, descricao: "energia", noMissing: true } },
      { module: "financeiro", phrase: "1.500,50", pending: () => pendingFrom("paguei salario do Joao"), expected: { tipo: "PAGAMENTO_FUNCIONARIO", exactTipo: true, funcionario_nome: "Joao", valor: 1500.5, noMissing: true } },
      { module: "financeiro", phrase: "racao", pending: () => pendingFrom("saida 300"), expected: { tipo: "DESPESA", exactTipo: true, valor: 300, descricao: "racao", noMissing: true } },
      financeParser("vendii leite por 900", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 900, descricao: "leite" }),
      financeParser("vendi leiti por 900", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 900, descricao: "leite" }),
      financeParser("recebi dinhero 800", { tipo: "RECEITA_VENDA", exactTipo: true, valor: 800 }),
      financeParser("despeza veterinario 600", { tipo: "DESPESA", exactTipo: true, valor: 600, descricao: "veterinario" }),
      financeParser("gastei con racao 400", { tipo: "DESPESA", exactTipo: true, valor: 400, descricao: "racao" }),
      financeParser("finaceiro do mes", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("quanto entro esse mes", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("quanto saiu ese mes", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("resutado do mes", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("como ta o financeiro do mes", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("financeiro do mes", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("resultado do mes", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("quanto entrou esse mes", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("quanto saiu esse mes", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("saldo financeiro", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("mostrar transacoes", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("entradas de hoje", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("saidas de hoje", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("financeiro de ontem", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("relatorio financeiro", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("me mostra o caixa", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("quanto vendemos esse mes", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("quanto gastamos esse mes", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("lucro do mes", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("resultado de hoje", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("transacoes da semana", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("despesas do mes", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("receitas do mes", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true }),
      financeParser("quais as minhas transacoes de hoje?", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje", financeiro_modo: "detalhado" }),
      financeParser("quais entradas de hoje?", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje", financeiro_tipo: "entrada", financeiro_modo: "detalhado" }),
      financeParser("quanto entrou hoje?", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje", financeiro_tipo: "entrada", financeiro_modo: "resumo" }),
      financeParser("quanto saiu hoje?", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje", financeiro_tipo: "saida", financeiro_modo: "resumo" }),
      financeParser("quanto gastei hoje?", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje", financeiro_tipo: "saida", financeiro_modo: "resumo" }),
      financeParser("quanto eu gastei hoje?", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje", financeiro_tipo: "saida", financeiro_modo: "resumo" }),
      financeParser("com o que eu gastei hoje?", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje", financeiro_tipo: "saida", financeiro_modo: "detalhado" }),
      financeParser("no que eu gastei hoje?", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje", financeiro_tipo: "saida", financeiro_modo: "detalhado" }),
      financeParser("quais foram meus gastos hoje?", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje", financeiro_tipo: "saida", financeiro_modo: "detalhado" }),
      financeParser("minhas despesas de hoje", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje", financeiro_tipo: "saida", financeiro_modo: "detalhado" }),
      financeParser("gastos de hoje", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje", financeiro_tipo: "saida", financeiro_modo: "detalhado" }),
      financeParser("despesas de hoje", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje", financeiro_tipo: "saida", financeiro_modo: "detalhado" }),
      financeParser("resultado do dia", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje", financeiro_modo: "resumo" }),
      financeParser("transacoes do mes", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "mes", financeiro_modo: "detalhado" }),
      financeParser("financeiro de hoje", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje", financeiro_modo: "resumo" }),
      financeParser("movimentacoes de ontem", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "ontem", financeiro_modo: "detalhado" }),
      financeParser("extrato da semana", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "semana", financeiro_modo: "detalhado" }),
      financeParser("quanto gastei com racao hoje?", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje", financeiro_tipo: "saida", filtro_texto: "racao" }),
      financeParser("vendas de leite do mes", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "mes", financeiro_tipo: "entrada", filtro_texto: "leite" }),
      financeParser("despesas com salario da semana", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "semana", financeiro_tipo: "saida", filtro_texto: "salario" }),
      financeParser("transacoes de 01/06/2026", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "2026-06-01", financeiro_modo: "detalhado" }),
      financeParser("transacoes de junho de 2026", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "2026-06", financeiro_modo: "detalhado" }),
      financeParser("finaceiro hj", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje" }),
      financeParser("resutado do dia", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje" }),
      financeParser("despezas de racao hoje", { tipo: "CONSULTA_FINANCEIRO", exactTipo: true, data_referencia: "hoje", financeiro_tipo: "saida", filtro_texto: "racao" }),
      financeParser("Joao entrou as 7:30", { tipo: "PONTO_FUNCIONARIO", exactTipo: true, funcionario_nome: "joao", ponto_tipo: "entrada", horario: "07:30" }),
      financeParser("comprei 10 sacos de racao por 300 reais", { tipo: "ESTOQUE_ENTRADA", exactTipo: true, compra: true, item: "Racao", quantidade: 10, unidade: "saco", valor: 300 })
    ];


    return { financeParser, eventParser, financeHumanParserTests };
  }
};
