module.exports = function loadBotTestSection(context) {
  with (context) {
    const inventoryHumanParserTests = [
      { phrase: "chegou 10 sacos de racao", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco" } },
      { phrase: "entrou 10 sacos de racao", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco" } },
      { phrase: "adicionar 10 sacos de racao", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco" } },
      { phrase: "registrar entrada de 10 sacos de racao", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco" } },
      { phrase: "chegaram 10 sacos de racao", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco" } },
      { phrase: "chegou racao 10 sacos", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco" } },
      { phrase: "racao entrou 10 sacos", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco" } },
      { phrase: "entrada racao 10 sacos", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco" } },
      { phrase: "botar 10 sacos de racao no estoque", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco" } },
      { phrase: "colocar 10 sacos de racao no estoque", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco" } },
      { phrase: "recebi 10 sacos de racao", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco" } },
      { phrase: "chegou 1 saco de racao", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 1, unidade: "saco", resumoIncludes: "1 saco" } },
      { phrase: "chegou 10,5 sacos de racao", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10.5, unidade: "saco" } },
      { phrase: "chegou dez sacos de racao", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco" } },
      { phrase: "chegou 20 kg de sal mineral", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Sal mineral", quantidade: 20, unidade: "kg" } },
      { phrase: "entrou 5 sacos de sal mineral", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Sal mineral", quantidade: 5, unidade: "saco" } },
      { phrase: "chegou 2 litros de carrapaticida", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "carrapaticida", quantidade: 2, unidade: "L" } },
      { phrase: "entrou 100 doses de vacina", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "vacina", quantidade: 100, unidade: "dose" } },
      { phrase: "comprei 50 seringas", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, compra: true, item: "seringas", quantidade: 50, missing: ["unidade"] } },
      { phrase: "chegou 200 kg de milho", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Milho", quantidade: 200, unidade: "kg" } },
      { phrase: "entrou 30 sacos de milho", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Milho", quantidade: 30, unidade: "saco" } },
      { phrase: "chegou 12 fardos de feno", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Feno", quantidade: 12, unidade: "fardo" } },
      { phrase: "comprei 8 rolos de arame", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, compra: true, item: "arame", quantidade: 8, unidade: "rolo", noMissing: true } },
      { phrase: "chegou 4 postes", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "postes", quantidade: 4, missing: ["unidade"] } },
      { phrase: "entrou 6 sacos de ureia", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "ureia", quantidade: 6, unidade: "saco" } },
      { phrase: "comprei 15 litros de diesel", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, compra: true, item: "diesel", quantidade: 15, unidade: "L", noMissing: true } },
      { phrase: "chegou 10 caixas de medicamento", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "medicamento", quantidade: 10, unidade: "caixa" } },
      { phrase: "chegou 5 frascos de antibiotico", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "antibiotico", quantidade: 5, unidade: "frasco" } },
      { phrase: "chegou 20 brincos de identificacao", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "identificacao", quantidade: 20, missing: ["unidade"] } },
      { phrase: "chegou 10 sacos de racao hoje", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco", data_referencia: "hoje" } },
      { phrase: "ontem chegou 10 sacos de racao", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco", data_referencia: "ontem" } },
      { phrase: "chegou 10 sacos de racao 2026-06-01", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco", data_referencia: "2026-06-01" } },
      { phrase: "entrada de racao 10 sacos 01/06/2026", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco", data_referencia: "2026-06-01" } },
      { phrase: "sal mineral 20kg ontem", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Sal mineral", quantidade: 20, unidade: "kg", data_referencia: "ontem" } },
      { phrase: "chegou 10 saco de racao", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco" } },
      { phrase: "chego 10 sacos de racao", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco" } },
      { phrase: "xegou 10 sacos de racao", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco" } },
      { phrase: "entrou 10 sako de racao", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco" } },
      { phrase: "racao 10 sc entrada", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", quantidade: 10, unidade: "saco" } },
      { phrase: "sal minaral 20kg", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Sal mineral", itemId: "item-sal-mineral", itemFound: true, quantidade: 20, unidade: "kg" } },
      { phrase: "usei 2 sacos de racao", expected: { tipo: "ESTOQUE_SAIDA", exactTipo: true, item: "Racao", quantidade: 2, unidade: "saco" } },
      { phrase: "saiu 2 sacos de racao", expected: { tipo: "ESTOQUE_SAIDA", exactTipo: true, item: "Racao", quantidade: 2, unidade: "saco" } },
      { phrase: "baixar 2 sacos de racao", expected: { tipo: "ESTOQUE_SAIDA", exactTipo: true, item: "Racao", quantidade: 2, unidade: "saco" } },
      { phrase: "dar baixa em 2 sacos de racao", expected: { tipo: "ESTOQUE_SAIDA", exactTipo: true, item: "Racao", quantidade: 2, unidade: "saco" } },
      { phrase: "retirei 2 sacos de racao", expected: { tipo: "ESTOQUE_SAIDA", exactTipo: true, item: "Racao", quantidade: 2, unidade: "saco" } },
      { phrase: "gastei 5 litros de diesel no trator", expected: { tipo: "ESTOQUE_SAIDA", exactTipo: true, item: "diesel", quantidade: 5, unidade: "L" } },
      { phrase: "usei 4 postes no piquete 2", expected: { tipo: "ESTOQUE_SAIDA", exactTipo: true, item: "postes", quantidade: 4, missing: ["unidade"] } },
      { phrase: "descartei 1 frasco vencido", expected: { tipo: "ESTOQUE_SAIDA", exactTipo: true, quantidade: 1, unidade: "frasco", missing: ["item_nome"] } },
      { phrase: "chegou racao", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "Racao", missing: ["quantidade"] } },
      { phrase: "chegou 10 sacos", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, quantidade: 10, unidade: "saco", missing: ["item_nome"] } },
      { phrase: "usei racao", expected: { tipo: "ESTOQUE_SAIDA", exactTipo: true, item: "Racao", missing: ["quantidade"] } },
      { phrase: "baixa 2 sacos", expected: { tipo: "ESTOQUE_SAIDA", exactTipo: true, quantidade: 2, unidade: "saco", missing: ["item_nome"] } },
      { phrase: "quanto tem de racao?", expected: { tipo: "CONSULTA_ESTOQUE_ITEM", exactTipo: true, item: "Racao", consulta: true } },
      { phrase: "estoque baixo", expected: { tipo: "CONSULTA_ESTOQUE_GERAL", exactTipo: true, consulta: true } },
      { phrase: "o que esta acabando?", expected: { tipo: "CONSULTA_ESTOQUE_GERAL", exactTipo: true, consulta: true } },
      { phrase: "chegou 10 sacos de item X-999", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "item X-999", quantidade: 10, unidade: "saco", itemUnresolved: true, itemFound: false } },
      { phrase: "comprei 70kg de arroz", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, compra: true, item: "arroz", quantidade: 70, unidade: "kg", itemUnresolved: true, itemFound: false, motivoIncludes: "item_nao_encontrado", noMissing: true } },
      { phrase: "comprei arroz 70kg", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, compra: true, item: "arroz", quantidade: 70, unidade: "kg", itemUnresolved: true, itemFound: false, noMissing: true } },
      { phrase: "compra de 70kg de arroz", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, compra: true, item: "arroz", quantidade: 70, unidade: "kg", itemUnresolved: true, itemFound: false, noMissing: true } },
      { phrase: "entrada de 70kg de arroz", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "arroz", quantidade: 70, unidade: "kg", itemUnresolved: true, itemFound: false, noMissing: true } },
      { phrase: "chegou 70kg de arroz", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "arroz", quantidade: 70, unidade: "kg", itemUnresolved: true, itemFound: false, noMissing: true } },
      { phrase: "coloca 70kg de arroz no estoque", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "arroz", quantidade: 70, unidade: "kg", itemUnresolved: true, itemFound: false, noMissing: true } },
      { phrase: "comprei 70kg de arroz por 200 reais", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, compra: true, item: "arroz", quantidade: 70, unidade: "kg", valor: 200, itemUnresolved: true, itemFound: false, motivoIncludes: "item_nao_encontrado", noMissing: true } },
      { phrase: "comprei 70 kilos de arroz", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, compra: true, item: "arroz", quantidade: 70, unidade: "kg", itemUnresolved: true, itemFound: false, noMissing: true } },
      { phrase: "comprei 70k de arroz", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, compra: true, item: "arroz", quantidade: 70, unidade: "kg", itemUnresolved: true, itemFound: false, noMissing: true } },
      { phrase: "comprei arroz 70k", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, compra: true, item: "arroz", quantidade: 70, unidade: "kg", itemUnresolved: true, itemFound: false, noMissing: true } },
      { phrase: "gastei 200 com 70kg de arroz", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, compra: true, item: "arroz", quantidade: 70, unidade: "kg", valor: 200, itemUnresolved: true, itemFound: false, noMissing: true } },
      { phrase: "paguei 300 em 10 sacos de racao", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, compra: true, item: "Racao", quantidade: 10, unidade: "saco", valor: 300, itemFound: true, noMissing: true } },
      { phrase: "gastei 70kg de arroz", expected: { tipo: "ESTOQUE_SAIDA", exactTipo: true, item: "arroz", quantidade: 70, unidade: "kg" } },
      { phrase: "paguei energia 400", expected: { tipo: "DESPESA", exactTipo: true, valor: 400, descricao: "energia" } },
      { phrase: "paguei salario do Joao 1500", expected: { tipo: "PAGAMENTO_FUNCIONARIO", exactTipo: true, funcionario_nome: "Joao", valor: 1500, pagamento_tipo: "salario" } },
      { phrase: "quanto tenho de arroz?", expected: { tipo: "CONSULTA_ESTOQUE_ITEM", exactTipo: true, item: "arroz", consulta: true, itemUnresolved: true, itemFound: false } },
      { phrase: "tem arroz no estoque?", expected: { tipo: "CONSULTA_ESTOQUE_ITEM", exactTipo: true, item: "arroz", consulta: true, itemUnresolved: true, itemFound: false } },
      { phrase: "comprei 5 doses de aftoza", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, compra: true, item: "Aftosa", quantidade: 5, unidade: "dose", itemFound: true, noMissing: true } },
      { phrase: "apliquei vacina na B-002", expected: { tipo: "VACINA_MEDICAMENTO", exactTipo: true, animal: "B-002", missing: ["produto"] } },
      { phrase: "chegou vacina 100 doses", expected: { tipo: "ESTOQUE_ENTRADA", exactTipo: true, item: "vacina", quantidade: 100, unidade: "dose" } },
      { phrase: "paguei 1000 na racao", expected: { tipo: "DESPESA", exactTipo: true, valor: 1000, descricao: "racao" } },
      { phrase: "B-002 deu 32 litros", expected: { tipo: "PRODUCAO_LEITE", exactTipo: true, animal: "B-002", litros: 32 } },
      { phrase: "oi", expected: { tipo: "DESCONHECIDO", exactTipo: true } },
      { phrase: "menu", expected: { tipo: "DESCONHECIDO", exactTipo: true } }
    ];


    return { inventoryHumanParserTests };
  }
};
