module.exports = function loadBotTestSection(context) {
  with (context) {
    const eventHumanParserTests = [
      eventParser("apliquei aftosa na B-002", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "aftosa", animal: "B-002" }),
      eventParser("vacina aftosa na vaca 15", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "aftosa", animal: "15" }),
      eventParser("B001 recebeu vacina aftosa", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "aftosa", animal: "B-001" }),
      eventParser("aplicar brucelose na novilha N-01", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "brucelose", animal: "N-01" }),
      eventParser("vacinei mimosa com aftosa", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "aftosa", animal: "B-001" }),
      eventParser("vacinei a B-002 hoje", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", animal: "B-002", data_referencia: "hoje", missing: ["produto"] }),
      eventParser("vacina da B-002 foi aftosa", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "aftosa", animal: "B-002" }),
      eventParser("a B-002 tomou aftosa", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "aftosa", animal: "B-002" }),
      eventParser("apliquei vacina contra aftosa na mimosa", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "aftosa", animal: "B-001" }),
      eventParser("vacina brucelose na A12", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "brucelose", animal: "A12" }),
      eventParser("B-002 vacinada com aftosa", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "aftosa", animal: "B-002" }),
      eventParser("registrar vacina aftosa animal B-002", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "aftosa", animal: "B-002" }),
      eventParser("apliquei vacina na vaca estrela", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", animal: "B-002", missing: ["produto"] }),
      eventParser("vacinei o rebanho com aftosa", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "aftosa", missing: ["animal_codigo"] }),
      eventParser("vacina clostridial na B001", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "clostridial", animal: "B-001" }),
      eventParser("aplicar raiva na vaca 002", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "raiva", animal: "002" }),
      eventParser("a mimosa recebeu vacina de raiva", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "raiva", animal: "B-001" }),
      eventParser("dose de aftosa na B-002", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "aftosa", animal: "B-002" }),
      eventParser("aftosa B-002", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "aftosa", animal: "B-002" }),
      eventParser("vacina B-002 aftosa", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "aftosa", animal: "B-002" }),
      eventParser("apliquei aftoza na B-002", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "aftosa", animal: "B-002" }),
      eventParser("vacina aftoza B002", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "aftosa", animal: "B-002" }),
      eventParser("vacinei mimosaa com aftosa", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", produto: "aftosa", animal: "B-001" }),
      eventParser("registrar vacina", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "vacina", missing: ["animal_codigo", "produto"] }),

      eventParser("mediquei a mimosa com vermifugo", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "vermifugo", animal: "B-001" }),
      eventParser("apliquei remedio na B-002", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "remedio", animal: "B-002" }),
      eventParser("B001 tomou antibiotico", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "antibiotico", animal: "B-001" }),
      eventParser("tratamento da estrela com vermifugo", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "vermifugo", animal: "B-002" }),
      eventParser("dei medicamento para vaca 15", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "medicamento", animal: "15" }),
      eventParser("apliquei terramicina na B-002", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "terramicina", animal: "B-002" }),
      eventParser("dei vermifugo na mimosa", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "vermifugo", animal: "B-001" }),
      eventParser("remedio para B001 foi antibiotico", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "antibiotico", animal: "B-001" }),
      eventParser("B-002 recebeu medicamento", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "medicamento", animal: "B-002" }),
      eventParser("medicar animal A12 com vermifugo", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "vermifugo", animal: "A12" }),
      eventParser("tratamento com antibiotico na vaca estrela", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "antibiotico", animal: "B-002" }),
      eventParser("dei dipirona na vaca B-002", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "dipirona", animal: "B-002" }),
      eventParser("apliquei anti-inflamatorio na B001", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "anti-inflamatorio", animal: "B-001" }),
      eventParser("vermifugo B-002", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "vermifugo", animal: "B-002" }),
      eventParser("B-002 vermifugo", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "vermifugo", animal: "B-002" }),
      eventParser("tratamento B-002 carrapaticida", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "carrapaticida", animal: "B-002" }),
      eventParser("passei carrapaticida no animal A12", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "carrapaticida", animal: "A12" }),
      eventParser("apliquei pour-on na B-002", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "pour-on", animal: "B-002" }),
      eventParser("dei suplemento na Mimosa", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "suplemento", animal: "B-001" }),
      eventParser("registrar tratamento", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", missing: ["animal_codigo", "produto"] }),
      eventParser("mediquei mimosa com vermifugo", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "vermifugo", animal: "B-001" }),
      eventParser("vermifugo b002", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "vermifugo", animal: "B-002" }),
      eventParser("apliquei remedio na b002", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "remedio", animal: "B-002" }),
      eventParser("tratameto da estrela com antibiotico", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, evento_tipo: "tratamento", produto: "antibiotico", animal: "B-002" }),

      eventParser("B-002 ficou doente", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes", novo_valor: "B-002 ficou doente" }),
      eventParser("a mimosa esta doente", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes" }),
      eventParser("vaca estrela esta mancando", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes" }),
      eventParser("B001 com febre", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes" }),
      eventParser("animal A12 com diarreia", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "A12", campo_alterado: "observacoes" }),
      eventParser("a vaca B-002 esta sem comer", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes" }),
      eventParser("mimosa com mastite", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes" }),
      eventParser("B-002 com carrapato", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes" }),
      eventParser("a novilha N-01 esta triste", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "N-01", campo_alterado: "observacoes" }),
      eventParser("animal 15 esta fraco", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "15", campo_alterado: "observacoes" }),
      eventParser("B001 esta tossindo", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes" }),
      eventParser("vaca estrela com ferida na pata", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes" }),
      eventParser("registrar doenca na Mimosa", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes" }),
      eventParser("observacao clinica B-002 febre", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes" }),
      eventParser("Mimosa precisa de veterinario", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes" }),
      eventParser("B-002 teve queda de producao e esta doente", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes" }),
      eventParser("animal A12 com problema no casco", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "A12", campo_alterado: "observacoes" }),
      eventParser("animal doente", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, campo_alterado: "observacoes", missing: ["animal_codigo"] }),
      eventParser("b002 fico doente", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes" }),
      eventParser("mimosa esta duente", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes" }),
      eventParser("vaca mancandoo", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, campo_alterado: "observacoes", missing: ["animal_codigo"] }),
      eventParser("B-002 ficou doente e custou 500 reais", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", valor: 500, resumoIncludes: "ocorrência clínica" }),
      eventParser("a vaca estrela ficou doente custou 500", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", valor: 500 }),
      eventParser("Mimosa teve mastite e gastei 220 no veterinario", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", valor: 220 }),
      eventParser("B001 com febre paguei 80 de remedio", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", valor: 80 }),
      eventParser("animal A12 machucado custo 150 reais", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "A12", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", valor: 150 }),
      eventParser("vaca 15 ferida na pata saiu 90 reais", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "15", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", valor: 90 }),
      eventParser("B-002 passando mal despesa veterinaria de 300 reais", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", valor: 300 }),
      eventParser("mimosa nao quer comer e custou 120 reais", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", valor: 120 }),
      eventParser("Estrela com problema no casco, veterinario ficou 250 reais", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", valor: 250 }),
      eventParser("a B-002 adoeceu e paguei 500", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", valor: 500 }),
      eventParser("B-002 ficou fraca e a consulta do veterinario deu 180 reais", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", valor: 180 }),
      eventParser("a novilha N-01 apareceu inchada e custou 75 reais", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "N-01", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", valor: 75 }),
      eventParser("B001 sangrando na pata paguei 60 reais", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", valor: 60 }),
      eventParser("veterinario veio na Mimosa porque ela esta doente e cobrou 400", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", valor: 400 }),

      eventParser("mimosa pariu hoje", { tipo: "PARTO", exactTipo: true, animal: "B-001", data_referencia: "hoje" }),
      eventParser("B-002 teve parto", { tipo: "PARTO", exactTipo: true, animal: "B-002" }),
      eventParser("vaca estrela pariu um bezerro", { tipo: "PARTO", exactTipo: true, animal: "B-002" }),
      eventParser("a Mimosa teve bezerro macho", { tipo: "PARTO", exactTipo: true, animal: "B-001" }),
      eventParser("B001 teve cria femea", { tipo: "PARTO", exactTipo: true, animal: "B-001" }),
      eventParser("nasceu bezerro da Mimosa", { tipo: "PARTO", exactTipo: true, animal: "B-001" }),
      eventParser("parto da vaca B-002", { tipo: "PARTO", exactTipo: true, animal: "B-002" }),
      eventParser("Mimosa pariu ontem", { tipo: "PARTO", exactTipo: true, animal: "B-001", data_referencia: "ontem" }),
      eventParser("B-002 teve parto dia 01/06/2026", { tipo: "PARTO", exactTipo: true, animal: "B-002", data_referencia: "2026-06-01" }),
      eventParser("nasceu uma bezerra da estrela", { tipo: "PARTO", exactTipo: true, animal: "B-002" }),
      eventParser("a vaca 15 deu cria", { tipo: "PARTO", exactTipo: true, animal: "15" }),
      eventParser("registrar nascimento de bezerro da B-002", { tipo: "PARTO", exactTipo: true, animal: "B-002" }),
      eventParser("001 pariu uma femea hoje", { tipo: "PARTO", exactTipo: true, animal: "001", data_referencia: "hoje", parto_cria_cadastro: true, cria_sexo: "femea", cria_categoria: "bezerra", missing: ["cria_codigo"] }),
      eventParser("001 pariu macho hoje, pai T-001", { tipo: "PARTO", exactTipo: true, animal: "001", data_referencia: "hoje", parto_cria_cadastro: true, cria_sexo: "macho", cria_categoria: "bezerro", pai_ref: "T-001", missing: ["cria_codigo"] }),
      eventParser("Mimosa pariu uma bezerra ontem", { tipo: "PARTO", exactTipo: true, animal: "B-001", data_referencia: "ontem", parto_cria_cadastro: true, cria_sexo: "femea", cria_categoria: "bezerra", missing: ["cria_codigo"] }),
      eventParser("B-001 pariu cria codigo C-123 femea hoje", { tipo: "PARTO", exactTipo: true, animal: "B-001", data_referencia: "hoje", parto_cria_cadastro: true, cria_sexo: "femea", cria_categoria: "bezerra", cria_codigo: "C-123", noMissing: true }),
      eventParser("001 pariu hoje", { tipo: "PARTO", exactTipo: true, animal: "001", data_referencia: "hoje" }),
      eventParser("parto complicado da B001", { tipo: "PARTO", exactTipo: true, animal: "B-001" }),
      eventParser("partu da mimosa", { tipo: "PARTO", exactTipo: true, animal: "B-001" }),
      eventParser("mimosa pariuu ontem", { tipo: "PARTO", exactTipo: true, animal: "B-001", data_referencia: "ontem" }),
      eventParser("parto", { tipo: "PARTO", exactTipo: true, missing: ["animal_codigo"] }),
      eventParser("aborto da vaca B-002", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes" }),

      eventParser("Mimosa entrou no cio", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes" }),
      eventParser("B-002 esta no cio", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes" }),
      eventParser("registrar cio da estrela", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes" }),
      eventParser("vaca 15 em cio", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "15", campo_alterado: "observacoes" }),
      eventParser("cio B001 hoje", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes" }),
      eventParser("a novilha N-01 apresentou cio", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "N-01", campo_alterado: "observacoes" }),
      eventParser("Mimosa esta prenha", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "fase", novo_valor: "gestante", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "prenhez" }),
      eventParser("B-002 esta gestante", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "fase", novo_valor: "gestante", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "prenhez" }),
      eventParser("confirmar prenhez da estrela", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "fase", novo_valor: "gestante", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "prenhez" }),
      eventParser("diagnostico positivo de prenhez na B001", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "fase", novo_valor: "gestante", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "prenhez" }),
      eventParser("vaca 15 vazia", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "15", campo_alterado: "fase", novo_valor: "vazia" }),
      eventParser("Mimosa nao esta prenha", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "fase", novo_valor: "vazia" }),
      eventParser("prenhez negativa na B-002", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "fase", novo_valor: "vazia" }),
      eventParser("inseminar Mimosa hoje", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "inseminacao" }),
      eventParser("Mimosa foi inseminada", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "inseminacao" }),
      eventParser("Thais foi inseminada", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "THAIS", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "inseminacao" }),
      eventParser("inseminaram a Thais", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "THAIS", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "inseminacao" }),
      eventParser("vaca 19 foi inseminada", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "19", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "inseminacao" }),
      eventParser("Amanda recebeu IA", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "AMANDA", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "inseminacao" }),
      eventParser("IA na vaca 19", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "19", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "inseminacao" }),
      eventParser("protocolo de inseminacao da 19", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "19", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "protocolo" }),
      eventParser("B-002 inseminada com semen do touro T-01", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "inseminacao", origem_inseminacao: "T-01" }),
      eventParser("cobertura da estrela com touro T-01", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "inseminacao", origem_inseminacao: "T-01" }),
      eventParser("B001 coberta pelo touro", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "inseminacao" }),
      eventParser("inseminacao da vaca 15 ontem", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "15", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "inseminacao", data_referencia: "ontem" }),
      eventParser("inseminacao da 19 dia 01.06.26", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "19", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "inseminacao", data_referencia: "2026-06-01" }),
      eventParser("registrar cobertura da Mimosa", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "inseminacao" }),
      eventParser("IA da B-002 com touro Holandes", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "inseminacao", origem_inseminacao: "Holandes" }),
      eventParser("Mimosa entrou em pre-parto", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "pre_parto" }),
      eventParser("pre-parto da Amanda hoje", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "AMANDA", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "pre_parto", data_referencia: "hoje" }),
      eventParser("ultimo protocolo da 090 nao passou", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "090", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "protocolo" }),
      eventParser("5714 CF nao passou", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "5714 CF", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "protocolo" }),
      eventParser("177 esta em reteste", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "177", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "reteste" }),
      eventParser("cioo da estrela", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes" }),
      eventParser("inseminacao da b002", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes" }),
      eventParser("prenhez da mimosaa", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "fase", novo_valor: "gestante", registro_evento_animal: true, evento_tipo: "reprodutivo", evento_reprodutivo_tipo: "prenhez" }),

      eventParser("historico da Mimosa", { tipo: "CONSULTA_ANIMAL", exactTipo: true, animal: "B-001", consulta: true }),
      eventParser("eventos da B-002", { tipo: "CONSULTA_ANIMAL", exactTipo: true, animal: "B-002", consulta: true }),
      eventParser("vacinas da B001", { tipo: "CONSULTA_ANIMAL", exactTipo: true, animal: "B-001", consulta: true }),
      eventParser("medicamentos da estrela", { tipo: "CONSULTA_ANIMAL", exactTipo: true, animal: "B-002", consulta: true }),
      eventParser("tratamentos da vaca 15", { tipo: "CONSULTA_ANIMAL", exactTipo: true, animal: "15", consulta: true }),
      eventParser("quando a Mimosa foi vacinada?", { tipo: "CONSULTA_ANIMAL", exactTipo: true, animal: "B-001", consulta: true }),
      eventParser("qual foi a ultima vacina da B-002?", { tipo: "CONSULTA_ANIMAL", exactTipo: true, animal: "B-002", consulta: true }),
      eventParser("historico clinico da estrela", { tipo: "CONSULTA_ANIMAL", exactTipo: true, animal: "B-002", consulta: true }),
      eventParser("partos da Mimosa", { tipo: "CONSULTA_ANIMAL", exactTipo: true, animal: "B-001", consulta: true }),
      eventParser("historico reprodutivo da B-002", { tipo: "CONSULTA_ANIMAL", exactTipo: true, animal: "B-002", consulta: true }),
      eventParser("eventos de hoje", { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "hoje" }),
      { module: "eventos-relatorios", phrase: "quais eventos ocorreram no rebanho?", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, consulta_registros: "eventos" } },
      { module: "eventos-relatorios", phrase: "eventos do rebanho", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, consulta_registros: "eventos" } },
      { module: "eventos-relatorios", phrase: "eventos de ontem", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "ontem", consulta_registros: "eventos" } },
      { module: "eventos-relatorios", phrase: "eventos da semana", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "semana", consulta_registros: "eventos" } },
      { module: "eventos-relatorios", phrase: "quais foram os partos recentes", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "recentes", periodo: "recentes", dias: 90, consulta_registros: "eventos", evento_tipo: "parto", consulta: true } },
      { module: "eventos-relatorios", phrase: "partos recentes", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "recentes", periodo: "recentes", dias: 90, consulta_registros: "eventos", evento_tipo: "parto", consulta: true } },
      { module: "eventos-relatorios", phrase: "ultimos partos", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "recentes", periodo: "recentes", dias: 90, consulta_registros: "eventos", evento_tipo: "parto", consulta: true } },
      { module: "eventos-relatorios", phrase: "relatorio dos partos", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "recentes", periodo: "recentes", dias: 90, consulta_registros: "eventos", evento_tipo: "parto", consulta: true } },
      { module: "eventos-relatorios", phrase: "relatorio dos partos recentes", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "recentes", periodo: "recentes", dias: 90, consulta_registros: "eventos", evento_tipo: "parto", consulta: true } },
      { module: "eventos-relatorios", phrase: "quais vacas pariram recentemente?", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "recentes", periodo: "recentes", dias: 90, consulta_registros: "eventos", evento_tipo: "parto", consulta: true } },
      { module: "eventos-relatorios", phrase: "lista das vacas que pariram", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "recentes", periodo: "recentes", dias: 90, consulta_registros: "eventos", evento_tipo: "parto", consulta: true } },
      { module: "eventos-relatorios", phrase: "partos das vacas", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "recentes", periodo: "recentes", dias: 90, consulta_registros: "eventos", evento_tipo: "parto", consulta: true } },
      { module: "eventos-relatorios", phrase: "partos dos ultimos 30 dias", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "ultimos_30", periodo: "ultimos_30", dias: 30, consulta_registros: "eventos", evento_tipo: "parto", consulta: true } },
      { module: "eventos-relatorios", phrase: "partos desse mes", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "mes", periodo: "mes", consulta_registros: "eventos", evento_tipo: "parto", consulta: true } },
      { module: "eventos-relatorios", phrase: "quem pariu recentemente", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "recentes", periodo: "recentes", dias: 90, consulta_registros: "eventos", evento_tipo: "parto", consulta: true } },
      { module: "eventos-relatorios", phrase: "ultimas inseminacoes", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "recentes", consulta_registros: "eventos", evento_tipo: "inseminacao" } },
      { module: "eventos-relatorios", phrase: "inseminacoes recentes", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "recentes", consulta_registros: "eventos", evento_tipo: "inseminacao" } },
      { module: "eventos-relatorios", phrase: "eventos reprodutivos recentes", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "recentes", consulta_registros: "eventos", evento_tipo: "reprodutivo" } },
      { module: "eventos-relatorios", phrase: "ultimos protocolos", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "recentes", consulta_registros: "eventos", evento_tipo: "protocolo" } },
      { module: "eventos-relatorios", phrase: "pre partos recentes", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "recentes", consulta_registros: "eventos", evento_tipo: "pre_parto" } },
      { module: "eventos-relatorios", phrase: "teve vacina hoje?", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "hoje", consulta_registros: "eventos", evento_tipo: "vacina" } },
      { module: "eventos-relatorios", phrase: "tratamentos de hoje", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "hoje", consulta_registros: "eventos", evento_tipo: "tratamento" } },
      { module: "eventos-relatorios", phrase: "teve animal doente hoje?", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "hoje", consulta_registros: "eventos", evento_tipo: "clinico" } },
      { module: "eventos-relatorios", phrase: "partos do mes", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "mes", consulta_registros: "eventos", evento_tipo: "parto" } },
      { module: "eventos-relatorios", phrase: "partos de hoje", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "hoje", consulta_registros: "eventos", evento_tipo: "parto" } },
      { module: "eventos-relatorios", phrase: "partos de maio", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "2026-05", consulta_registros: "eventos", evento_tipo: "parto" } },
      { module: "eventos-relatorios", phrase: "Mimosa pariu recentemente", expected: { tipo: "PARTO", exactTipo: true, animal: "B-001" } },
      { module: "eventos-relatorios", phrase: "cios registrados", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, consulta_registros: "eventos", evento_tipo: "reprodutivo" } },
      { module: "eventos-relatorios", phrase: "relatorio de hoje", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "hoje", consulta_registros: "relatorio" } },
      { module: "eventos-relatorios", phrase: "resumo do mes", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "mes", consulta_registros: "relatorio" } },
      { module: "eventos-relatorios", phrase: "relatorio da semana", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "semana", consulta_registros: "relatorio" } },
      { module: "eventos-relatorios", phrase: "relatorio dos ultimos 7 dias", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "ultimos_7", consulta_registros: "relatorio" } },
      { module: "eventos-relatorios", phrase: "relatorio dos ultimos 30 dias", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "ultimos_30", consulta_registros: "relatorio" } },
      { module: "eventos-relatorios", phrase: "relatorio da semana passada", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "semana_passada", consulta_registros: "relatorio" } },
      { module: "eventos-relatorios", phrase: "relatorio do mes passado", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "mes_passado", consulta_registros: "relatorio" } },
      { module: "eventos-relatorios", phrase: "relatorio deste ano", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "ano", consulta_registros: "relatorio" } },
      { module: "eventos-relatorios", phrase: "relatorio de junho", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, consulta_registros: "relatorio" } },
      { module: "eventos-relatorios", phrase: "esta indo bem?", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, consulta_registros: "relatorio", relatorio_modo: "analise" } },
      { module: "eventos-relatorios", phrase: "resumo rapido", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, consulta_registros: "relatorio", relatorio_modo: "rapido" } },
      { module: "eventos-relatorios", phrase: "relatorio detalhado", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, consulta_registros: "relatorio", relatorio_modo: "detalhado" } },
      { module: "eventos-relatorios", phrase: "alertas hj", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "hoje", consulta_registros: "alertas" } },
      { module: "eventos-relatorios", phrase: "eventos do rebanio", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, consulta_registros: "eventos" } },
      { module: "eventos-relatorios", phrase: "relatirio de hoje", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "hoje", consulta_registros: "relatorio" } },
      { module: "eventos-relatorios", phrase: "resumo do mez", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true, data_referencia: "mes", consulta_registros: "relatorio" } },
      { module: "eventos-relatorios", phrase: "relatorio", expected: { tipo: "CONSULTA_REGISTROS_HOJE", exactTipo: true } },

      eventParser("Lindona não comeu hoje", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "Lindona", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", novoValorIncludes: "não comeu", data_referencia: "hoje", resumoIncludes: "ocorrência clínica" }),
      eventParser("B-002 não comeu hoje", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", novoValorIncludes: "não comeu", data_referencia: "hoje", resumoIncludes: "ocorrência clínica" }),
      eventParser("a preta tá mancando hoje", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "PRETA", campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", novoValorIncludes: "mancando", data_referencia: "hoje", resumoIncludes: "ocorrência clínica" }),
      eventParser("tem vaca doente", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, campo_alterado: "observacoes", registro_evento_animal: true, evento_tipo: "clinico", novoValorIncludes: "vaca doente", missing: ["animal_codigo"] }),

      eventParser("B-002", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, animal: "B-002", missing: ["produto"] }, { pending: () => pendingFrom("registrar vacina") }),
      eventParser("Aftosa", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, animal: "B-002", produto: "Aftosa", noMissing: true }, { pending: () => pendingFrom("registrar vacina", ["B-002"]) }),
      eventParser("Vermifugo", { tipo: "VACINA_MEDICAMENTO", exactTipo: true, animal: "B-002", produto: "Vermifugo", noMissing: true }, { pending: () => pendingFrom("registrar tratamento", ["B-002"]) }),
      eventParser("febre", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-001", campo_alterado: "observacoes", noMissing: true }, { pending: () => pendingFrom("animal doente", ["B001"]) }),
      eventParser("nao foi ontem", { tipo: "PARTO", exactTipo: true, animal: "B-001", data_referencia: "ontem", noMissing: true }, { pending: () => pendingFrom("Mimosa pariu hoje") }),
      eventParser("B-002", { tipo: "ATUALIZACAO_ANIMAL", exactTipo: true, animal: "B-002", campo_alterado: "observacoes", noMissing: true }, { pending: () => pendingFrom("registrar cio") }),

      eventParser("Mimosa ontem", { tipo: "DESCONHECIDO", exactTipo: true }),
      eventParser("B-002 5 ml", { tipo: "DESCONHECIDO", exactTipo: true }),
      eventParser("geneologia clinica", { tipo: "DESCONHECIDO", exactTipo: true })
    ];


    return { eventHumanParserTests };
  }
};
